config:
  install_tree:
    # Completely ignoring lower-precedence configuration options is supported with the :: notation for keys
    root:: $spack/../upstream
  # Available in v0.20.0
  source_cache: $spack/../sourcecache
  # Available in v0.20.0
  environments_root: $spack/../environments
  # Increasing from 1 minute to 10 minutes to allow for concurrent builds
  # to wait longer for .spack-db lock rather than exiting early.
  db_lock_timeout: 600
  # Set deprecated to true, to avoid:
  # Error: Version requirement 3.31.6 on cmake for cmake cannot match any
  #        known version from package.py or externals
  # As well as other concretization failures for deprecated packages on newer versions of spack
  deprecated: true