config:
  install_tree:
    # Completely ignoring lower-precedence configuration options is supported with the :: notation for keys
    root:: $spack/../upstream
  # Available in v0.20.0
  source_cache: $spack/../sourcecache
  # Available in v0.20.0
  environments_root: $spack/../environments
  # Set deprecated to true, to avoid concretization failures for deprecated packages on newer versions of spack
  deprecated: true
