# This scope is used to manage UK Met Office restricted packages.
# It's used in environment-level configuration to override install paths
# in ACCESS-ESM1.5 and ACCESS-ESM1.6 MDRs to locked down locations.
config:
  install_tree:
    root: $spack/../restricted/ukmo/release
  source_cache: $spack/../restricted/ukmo/source_cache
  build_stage:
    - $TMPDIR/restricted/spack-stage
